version: "3.7"
services: 
    db:
        image: mcr.microsoft.com/mssql/server
        environment:
            SA_PASSWORD: "ZAQ!2wsx"
            ACCEPT_EULA: "Y"

    rabbitMq:
        image: rabbitmq:3.8-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672